interface ImportMetaEnv {
  VITE_APP_TITLE: string;
  VITE_GITHUB_URL: string;
  VITE_GITHUB_ACCESS_TOKEN_PART1: string;
  VITE_GITHUB_ACCESS_TOKEN_PART2: string;
  VITE_GITHUB_OWNER: string;
  VITE_GITHUB_REPO: string;
  VITE_GITHUB_MILESTONE_POSTS: string;
  VITE_GITHUB_MILESTONE_SNIPPETS: string;
  VITE_ARTICLE_PAGE_SIZE: string;
  VITE_COMMENT_PAGE_SIZE: string;
}
